# Generated by Django 3.2 on 2021-05-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('anon', models.CharField(default='', max_length=250, verbose_name='Анонс')),
                ('full', models.TextField(verbose_name='Текст')),
                ('table', models.IntegerField(verbose_name='стол')),
                ('guests', models.IntegerField(verbose_name='количество')),
                ('vdate', models.DateField(verbose_name='vДата')),
                ('vtime', models.TimeField(verbose_name='vВремя')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
