# Generated by Django 3.2 on 2021-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='anon',
            field=models.CharField(default='Отсутствует', max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='art',
            name='full',
            field=models.TextField(verbose_name='-'),
        ),
        migrations.AlterField(
            model_name='art',
            name='guests',
            field=models.IntegerField(default='1', verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='art',
            name='table',
            field=models.IntegerField(default='1', verbose_name='стол'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(default='Без имени', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='art',
            name='vdate',
            field=models.DateField(default='01.01.2001', verbose_name='vДата'),
        ),
        migrations.AlterField(
            model_name='art',
            name='vtime',
            field=models.TimeField(default='12:00', verbose_name='vВремя'),
        ),
    ]
