# Generated by Django 3.2 on 2021-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210531_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='anon',
            field=models.CharField(default='', max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='art',
            name='full',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='art',
            name='vdate',
            field=models.DateField(default='01/01/2001', verbose_name='vДата'),
        ),
    ]
