# Generated by Django 3.2 on 2021-05-31 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210531_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='anon',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='art',
            name='full',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='art',
            name='guests',
            field=models.IntegerField(default='1', null=True, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='art',
            name='table',
            field=models.IntegerField(default='1', null=True, verbose_name='стол'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='art',
            name='vdate',
            field=models.DateField(default=datetime.date(2021, 5, 31), verbose_name='vДата'),
        ),
    ]
