# Generated by Django 3.2 on 2021-05-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_art_vdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='vdate',
            field=models.DateField(default='2021-05-31', verbose_name='vДата'),
        ),
    ]
