# Generated by Django 3.2 on 2021-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_art_vdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='anon',
            field=models.CharField(default='', max_length=250, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='art',
            name='full',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='art',
            name='guests',
            field=models.IntegerField(default='1', verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='art',
            name='table',
            field=models.IntegerField(default='1', verbose_name='стол'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
